Matissa/Models/DetallePedido.cs
using System;
using System.Collections.Generic;

namespace Matissa.Models
{
    public partial class Detallepedido
    {
        public int IdDetallePedido { get; set; }
        public int IdProducto { get; set; }
        public int IdPedido { get; set; }
        public int CantidadProducto { get; set; }
        public float PrecioUnitario { get; set; }

        public virtual Pedido IdPedidoNavigation { get; set; } = null!;
        public virtual Producto IdProductoNavigation { get; set; } = null!;
    }
}

Matissa/Controllers/DetallePedidosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Matissa.Models;

using X.PagedList;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.AspNetCore.Authorization;

namespace Matissa.Controllers
{
    [Authorize(Roles = "Administrador,Clientes")]
    public class DetallePedidosController : Controller
    {
        private readonly dbMatissaNETContext _context;
        private static List<PedidoModel> pedidoModels = new List<PedidoModel>();

        public DetallePedidosController(dbMatissaNETContext context)
        {
            _context = context;
        }

        // GET: DetallePedidos
        public async Task<IActionResult> Index()
        {
            var dbMatissaNETContext = _context.DetallePedidos.Include(p => p.IdPedidoNavigation).Include(c => c.IdProductoNavigation);
            return View(await dbMatissaNETContext.ToListAsync());
        }

        // GET: DetallePedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DetallePedidos == null)
            {
                return NotFound();
            }

            var detallePedido = await _context.DetallePedidos
                .Include(d => d.IdPedidoNavigation)
                .Include(d => d.IdProductoNavigation)
                .FirstOrDefaultAsync(m => m.IdDetallePedido == id);
            if (detallePedido == null)
            {
                return NotFound();
            }

            return View(detallePedido);
        }

        [HttpGet]
        public IActionResult AgregarProducto(PedidoModel model)
        {
            pedidoModels.Add(model);

            // Puedes realizar otras operaciones con el detalle si es necesario
            Console.WriteLine($"Detalle recibido:{model.IdProducto} {model.Nombre} {model.Cantidad} {model.Subtotal}");
            foreach (var detall in pedidoModels)
            {
                Console.WriteLine($"Detalle almacenado:{detall.IdProducto} {detall.Nombre} {detall.Cantidad} {detall.Subtotal}");
            }
            return Json(new { success = true, message = "Detalle guardado" });
        }

        [HttpGet]
        public IActionResult RemoveProducto(int idProducto)
        {
            PedidoModel productoRemove = pedidoModels.FirstOrDefault(d => d.IdProducto == idProducto);
            if (productoRemove != null)
            {
                pedidoModels.Remove(productoRemove);
                Console.WriteLine($"Detalle con ID {productoRemove.IdProducto} eliminado.");
            }
            else
            {
                Console.WriteLine($"Detalle no encontrado.");
            }
            Console.WriteLine("Lista después de la eliminación:");
            foreach (var detalle in pedidoModels)
            {
                Console.WriteLine($"ID: {detalle.IdProducto}");
            }
            return Json(new { success = true, message = "Detalle guardado" });
        }

        [HttpGet]
        public IActionResult DataProducto(int idProducto)
        {
            var producto = _context.Productos.Find(idProducto);
            if (producto == null)
            {
                return NotFound();
            }
            return Ok(producto);
        }

        // GET: DetallePedidos/Create
        public IActionResult Create()
        {
            foreach (var detall in pedidoModels)
            {
                Console.WriteLine($"Detalles almacenados:{detall.IdProducto} {detall.Nombre} {detall.Cantidad} {detall.Subtotal}");
            }
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto");
            return View();
        }

        // POST: DetallePedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDetallePedido,IdProducto,IdPedido,CantidadProducto,PrecioUnitario")] DetallePedido detallePedido)
        {
            if (detallePedido != null)
            {
                var idPedido = ObtenerPedidoID();
                var totalPedido = 0;
                var pedidoRemove = false;
                foreach (var item in pedidoModels)
                {
                    var producto = _context.Productos.Find(item.IdProducto);
                    Console.WriteLine(producto.SaldoInventario);
                    Console.WriteLine("###############################################################");
                    if (item.Cantidad <= producto.SaldoInventario)
                    {
                        var idDetallePedido = ObtenerDetallePedidoID();
                        detallePedido.IdDetallePedido = idDetallePedido;
                        detallePedido.IdPedido = idPedido;

                        detallePedido.IdProducto = item.IdProducto;
                        detallePedido.CantidadProducto = item.Cantidad;
                        detallePedido.PrecioUnitario = item.Subtotal;

                        _context.DetallePedidos.Add(detallePedido);
                        await _context.SaveChangesAsync();

                        totalPedido += item.Subtotal;


                        producto.SaldoInventario -= item.Cantidad;
                        _context.Productos.Update(producto);
                    }
                    else
                    {
                        var idLastPedido = ObtenerPedidoID();
                        var dataPedido = _context.Pedidos.Find(idLastPedido);
                        if (dataPedido != null)
                        {
                            _context.Pedidos.Remove(dataPedido);
                            _context.SaveChanges();
                            pedidoModels.Clear();
                            pedidoRemove = true;
                        }

                        TempData["Mensaje"] = "No hay suficientes productos para crear el pedido";
                        return RedirectToAction("Index", "Pedidos");
                    }
                }
                if (!pedidoRemove)
                {
                    var pedido = _context.Pedidos.Find(idPedido);
                    if (pedido != null)
                    {

                        pedido.PrecioTotalPedido = totalPedido;
                        _context.Pedidos.Update(pedido);
                        await _context.SaveChangesAsync();
                        pedidoModels.Clear();
                    }
                }
                pedidoModels.Clear();
                return RedirectToAction("Index", "Pedidos");
            }
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "NombreProducto", detallePedido.IdProducto);
            return NotFound(detallePedido);

        }
        public int ObtenerPedidoID()
        {
            var idPedido = _context.Pedidos.Max(p => (int?)p.IdPedido) ?? 1;
            return idPedido;
        }
        public int ObtenerDetallePedidoID()
        {
            var idDetallePedido = _context.DetallePedidos.Max(p => (int?)p.IdDetallePedido) ?? 0;
            return idDetallePedido + 1;
        }

        // GET: DetallePedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DetallePedidos == null)
            {
                return NotFound();
            }

            var detallePedido = await _context.DetallePedidos.FindAsync(id);
            if (detallePedido == null)
            {
                return NotFound();
            }
            ViewData["IdPedido"] = new SelectList(_context.Pedidos, "IdPedido", "IdPedido", detallePedido.IdPedido);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detallePedido.IdProducto);
            return View(detallePedido);
        }

        // POST: DetallePedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDetallePedido,IdProducto,IdPedido,CantidadProducto,PrecioUnitario")] DetallePedido detallePedido)
        {
            if (id != detallePedido.IdDetallePedido)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detallePedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetallePedidoExists(detallePedido.IdDetallePedido))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPedido"] = new SelectList(_context.Pedidos, "IdPedido", "IdPedido", detallePedido.IdPedido);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detallePedido.IdProducto);
            return View(detallePedido);
        }

        // GET: DetallePedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DetallePedidos == null)
            {
                return NotFound();
            }

            var detallePedido = await _context.DetallePedidos
                .Include(d => d.IdPedidoNavigation)
                .Include(d => d.IdProductoNavigation)
                .FirstOrDefaultAsync(m => m.IdDetallePedido == id);

Matissa/Views/DetallePedidos/Create.cshtml
@model Matissa.Models.DetallePedido
<link rel="stylesheet" href="~/css/pedido.css" asp-append-version="true" />
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-light p-3 text-center" style="background-color: #3cc3bd">
    <h1 class="merienda">Listado de pedidos</h1>
</div>

@{
    var mensaje = TempData["Mensaje"] as string;
}
@if (!string.IsNullOrEmpty(mensaje))
{
    <div class="alert-warning p-2 text-center">
        @mensaje
    </div>
}

<div class="container mt-5 mb-3">
    <form asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-5">
                <div class="form-group">
                    <label asp-for="IdProducto" class="control-label">Seleccione producto</label>
                    <select asp-for="IdProducto" id="idProducto" data-url="@Url.Action("DataProducto", "DetallePedidos")" class="form-control rounded-pill" onchange="dataProducto();" asp-items="ViewBag.IdProducto">
                        <option disabled selected>-- Seleccione producto --</option>
                    </select>
                </div>
                <div class="form-group">
                    <input class="form-control rounded-pill" id="nombre" readonly/>
                </div>
            </div>
            <div class="col-5">
                <div class="form-group">
                    <label asp-for="CantidadProducto" class="control-label">Cantidad</label>
                    <input asp-for="CantidadProducto" id="cantidad" min="1" class="form-control rounded-pill" />
                    <span asp-validation-for="CantidadProducto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input class="form-control rounded-pill" id="precio" readonly />
                </div>
            </div>
        </div>
        <div class="form-group text-center">
            <input type="submit" value="Aceptar" class="btn acept-btn" />
            <a asp-action="DeletePedido" asp-controller="DetallePedidos">
                <input type="button" class="btn cancel-btn" value="Cancelar" />
            </a>
        </div>
    </form>
    <div class="row">
        <div class="col-3 mb-3 agregarProducto">
            <button type="button" class="btn cancel-btn" id="btnAgregarP" onclick="agregarProducto()" style="width: 100%">
                Agregar producto
                <i class="fa-solid fa-plus"></i>
            </button>
        </div>
    </div>
    <div class="container container-tabla">
        <table class="tabla text-center" id="tablaProductos">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Código</th>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>

    </div>
</div>

<script>
    var listProducts = [];
    var cantidadActual = 0;
    function agregarProducto() {
        let producto = document.getElementById("idProducto").value;
        let nombre = document.getElementById("nombre").value;
        let cantidad = document.getElementById("cantidad").value;
        let precio = document.getElementById("precio").value;

        var subtotal = precio * cantidad;

        var obj = {
            idProducto: producto,
            nombre: nombre,
            cantidad: cantidad,
            subtotal: subtotal
        }
        if (cantidadActual >= cantidad) {
            let indiceRegister = listProducts.findIndex(detalle => detalle.idProducto === producto);
            if (indiceRegister == -1 && cantidad > 0) {
                listProducts.push(obj);

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("AgregarProducto","DetallePedidos")", // Reemplaza con la URL de tu controlador
                    contentType: "application/json; charset=utf-8",
                    data: obj,
                    success: function (response) {
                        // Manejar la respuesta del servidor si es necesario
                        console.log(response.message);

                    },
                    error: function (error) {
                        console.error("Error al guardar detalles", error);
                    }
                });

                mostrarDetalles();
            } else {
                if (cantidad < 1) {
                    Swal.fire({
                        icon: "error",
                        title: "Error",
                        text: "Cantidad no válida",
                    });
                } else {
                    Swal.fire({
                        icon: "error",
                        title: "Error",
                        text: "El producto ya existe en la lista",
                    });
                }
            }
        } else {
            Swal.fire({
                icon: "error",
                title: "Error",
                text: "No hay suficientes productos",
            });
        }
    }

    function mostrarDetalles() {
        // Limpiar el contenido actual del tbody
        var tbody = document.getElementById("tablaProductos").getElementsByTagName("tbody")[0];
        tbody.innerHTML = "";
        // Crear las filas con detalles y agregarlas al tbody
        for (var i = 0; i < listProducts.length; i++) {
            var detalle = listProducts[i];

            // Crear una nueva fila en el tbody
            var row = tbody.insertRow(i);

            // Insertar celdas con los datos del detalle en la fila
            var cellIndex = row.insertCell(0);
            cellIndex.innerHTML = i + 1;

            var cellProducto = row.insertCell(1);
            cellProducto.innerHTML = detalle.idProducto;

            var cellNombre = row.insertCell(2);
            cellNombre.innerHTML = detalle.nombre;

            var cellCantidad = row.insertCell(3);
            cellCantidad.innerHTML = detalle.cantidad;

            var a = detalle.subtotal; // Supongo que detalle.subtotal es tu número
            var precioFormat = a.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

            var cellSubtotal = row.insertCell(4);
            cellSubtotal.innerHTML = precioFormat;


            // var cellSubtotal = row.insertCell(4);
            // cellSubtotal.innerHTML = detalle.subtotal;

            var cellDelete = row.insertCell(5);
            cellDelete.innerHTML = `
            <button type="button" class="btn btn-warning" onclick="removeProducto(${detalle.idProducto})">
                <i class="fa-solid fa-trash"></i>
            </button>`
            // Puedes agregar más celdas según sea necesario
        }
    }
   
    function removeProducto(idProducto) {
        let indiceRemove = listProducts.findIndex(detalle => detalle.idProducto === idProducto);
        listProducts.splice(indiceRemove, 1);

        $.ajax({
            url: "@Url.Action("RemoveProducto","DetallePedidos")",
            type: "GET",
            data: { idProducto: idProducto },
            success: function (response) {
                console.log(response.message);
            },
            error: function (error) {
                console.error("Error al guardar detalles", error);
            }
        });

        mostrarDetalles();
    }

    function dataProducto() {
        $(document).ready(function () {
            var productId = $("#idProducto").val(); // Obtener el ID del producto desde algún lugar en tu página
            $.ajax({
                url: $("#idProducto").data("url"), // Ruta al controlador y acción
                type: "GET",
                data: { idProducto: productId },
                success: function (data) {
                    // Manejar los datos del producto devueltos por el servidor
                    let precio = document.getElementById("precio").value = data.precioVenta;
                    let nombre = document.getElementById("nombre").value = data.nombreProducto;
                    cantidadActual = data.saldoInventario;
                    console.log(data);
                    // Aquí puedes actualizar tu interfaz de usuario con los datos del producto
                },
                error: function () {
                    alert("Error al obtener los datos del producto");
                }
            });
        });
    }
    
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Matissa/Views/DetallePedidos/Delete.cshtml
@model Matissa.Models.DetallePedido

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetallePedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadProducto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadProducto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPedidoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPedidoNavigation.IdPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProductoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoNavigation.IdProducto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdDetallePedido" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Matissa/Views/DetallePedidos/Details.cshtml
@model Matissa.Models.DetallePedido

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>DetallePedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadProducto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadProducto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPedidoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPedidoNavigation.IdPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProductoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoNavigation.IdProducto)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdDetallePedido">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Matissa/Views/DetallePedidos/Edit.cshtml
@model Matissa.Models.DetallePedido

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>DetallePedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdDetallePedido" />
            <div class="form-group">
                <label asp-for="IdProducto" class="control-label"></label>
                <select asp-for="IdProducto" class="form-control" asp-items="ViewBag.IdProducto"></select>
                <span asp-validation-for="IdProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdPedido" class="control-label"></label>
                <select asp-for="IdPedido" class="form-control" asp-items="ViewBag.IdPedido"></select>
                <span asp-validation-for="IdPedido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadProducto" class="control-label"></label>
                <input asp-for="CantidadProducto" class="form-control" />
                <span asp-validation-for="CantidadProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioUnitario" class="control-label"></label>
                <input asp-for="PrecioUnitario" class="form-control" />
                <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Matissa/Views/DetallePedidos/Index.cshtml
@using X.PagedList;
@model IPagedList<Matissa.Models.Pedido>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<link rel="stylesheet" href="~/css/pedido.css" asp-append-version="true" />
@{
    <div class="text-light p-3 text-center" style="background-color: #3cc3bd">
        <h1 class="merienda">Listado de pedidos</h1>
    </div>
    <div class="container mt-5">
        <div class="container mb-5">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-floating search">
                        <form asp-controller="DetallePedidos" asp-action="Index">
                            <input type="text" class="form-control rounded-pill" name="buscar" placeholder="Buscar..." />
                        </form>
                    </div>
                </div>
                <div class="col-sm-4">
                    <a class="btn create-pedido rounded-pill" asp-action="Create" asp-controller="DetallePedidos">
                        Generar reporte de pedidos
                    </a>
                </div>
                <div class="col-sm-4">
                    <a class="btn create-pedido rounded-pill" asp-action="Create" asp-controller="Pedidos">
                        Crear pedido
                        <span class="material-icons">
                            shopping_bag
                        </span>
                    </a>
                </div>
            </div>
        </div>

        @if (Model.Count() > 0)
        {

        }
        else
        {
            <p>No exiten registros</p>
        }
    </div>
    <div class="pagination-container">
        @if (Model != null && Model.PageCount > 1)
        {
            <div class="d-flex justify-content-center mb-5">
                <nav aria-label="Page navigation bg-dark">
                    <ul class="pagination">

                        <!-- Botón para la página anterior (oculto en la página 1) -->
                        <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
                            <a class="page-link" href="?page=@(Model.PageNumber - 1)" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>

                        <!-- Iterar sobre las páginas disponibles -->
                        @for (var i = 1; i <= Model.PageCount; i++)
                        {
                            <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                                <a class="page-link" href="?page=@i">@i</a>
                            </li>
                        }

                        <!-- Botón para la página siguiente (oculto en la última página) -->
                        <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
                            <a class="page-link" href="?page=@(Model.PageNumber + 1)" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>

                    </ul>
                </nav>
            </div>
        }
    </div>
}