Matissa/Models/Servicio.cs
using System;
using System.Collections.Generic;

namespace Matissa.Models
{
    public partial class Servicio
    {
        public Servicio()
        {
            Detallecita = new HashSet<Detallecitum>();
        }

        public int IdServicio { get; set; }
        public int IdEmpleado { get; set; }
        public string NombreServicio { get; set; } = null!;
        public string? Descripcion { get; set; }
        public int Duracion { get; set; }
        public float Precio { get; set; }
        public sbyte Estado { get; set; }

        public virtual Empleado IdEmpleadoNavigation { get; set; } = null!;
        public virtual ICollection<Detallecitum> Detallecita { get; set; }
    }
}

Matissa/Controllers/ServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Matissa.Models;

namespace Matissa.Controllers
{
    public class ServiciosController : Controller
    {
        private readonly dbMatissaNETContext _context;

        public ServiciosController(dbMatissaNETContext context)
        {
            _context = context;
        }

        // GET: Servicios
        public async Task<IActionResult> Index()
        {
            var dbMatissaNETContext = _context.Servicios;
            return View(await dbMatissaNETContext.ToListAsync());
        }

        // GET: Servicios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .FirstOrDefaultAsync(m => m.IdServicio == id);
            if (servicio == null)
            {
                return NotFound();
            }

            return View(servicio);
        }

        // GET: Servicios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servicios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdServicio,NombreServicio,Descripción,Duración,Precio,Estado")] Servicio servicio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(servicio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(servicio);
        }

        // GET: Servicios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios.FindAsync(id);
            if (servicio == null)
            {
                return NotFound();
            }
            return View(servicio);
        }

        // POST: Servicios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdServicio,NombreServicio,Descripción,Duración,Precio,Estado,IdTipoServicio")] Servicio servicio)
        {
            if (id != servicio.IdServicio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(servicio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicioExists(servicio.IdServicio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(servicio);
        }

        // GET: Servicios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .FirstOrDefaultAsync(m => m.IdServicio == id);
            if (servicio == null)
            {
                return NotFound();
            }

            return View(servicio);
        }

        // POST: Servicios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Servicios == null)
            {
                return Problem("Entity set 'dbMatissaNETContext.Servicios'  is null.");
            }
            var servicio = await _context.Servicios.FindAsync(id);
            if (servicio != null)
            {
                _context.Servicios.Remove(servicio);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServicioExists(int id)
        {
          return (_context.Servicios?.Any(e => e.IdServicio == id)).GetValueOrDefault();
        }
    }
}

Matissa/Views/Servicios/Create.cshtml
@model Matissa.Models.Servicio

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/servicios/servicios.css">
<div class="container-fluid titulo-citas">
    <div class="row">
        <div class="col-12">
            <h1>Crear servicio</h1>
        </div>
    </div>
</div>
<div class="col-12 texto-quicksand">
    <form asp-action="Create">
        <div class="row ">
            <div class="col-sm-3 ">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group text-center">
                    <label asp-for="IdServicio" class="control-label texto-quicksand"></label>
                    <input asp-for="IdServicio" class="form-control rounded-pill custom-input" />
                    <span asp-validation-for="IdServicio" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group text-center">
                    <label asp-for="NombreServicio" class="control-label"></label>
                    <input asp-for="NombreServicio" class="form-control rounded-pill custom-input" />
                    <span asp-validation-for="NombreServicio" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group text-center">
                    <label asp-for="Descripción" class="control-label"></label>
                    <input asp-for="Descripción" class="form-control rounded-pill custom-input" />
                    <span asp-validation-for="Descripción" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group text-center">
                    <label asp-for="Duración" class="control-label"></label>
                    <input asp-for="Duración" class="form-control rounded-pill custom-input" />
                    <span asp-validation-for="Duración" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group text-center">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control rounded-pill custom-input" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group text-center">
                    <label asp-for="Estado" class="control-label"></label>
                    <input asp-for="Estado" class="form-control rounded-pill custom-input" />
                    <span asp-validation-for="Estado" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row pt-3 justify-content-center">
            <div class="col-md-4">
                <div class="form-group text-center">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="btn btn-dark" asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>


    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Matissa/Views/Servicios/Delete.cshtml
@model Matissa.Models.Servicio

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container text-center" style="width: 100%">
    <link rel="stylesheet" href="~/css/citas/Citums.css">
    <div class="container-fluid titulo-citas" >
        <div class="row">
            <div class="col-12">
                <h1>Eliminar Servicio</h1>
            </div>
        </div>
    </div>

        <div>
            <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreServicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreServicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripción)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripción)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duración)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duración)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdServicio" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-dark" asp-action="Index">Back to List</a>
    </form>
</div>
</div>

Matissa/Views/Servicios/Details.cshtml
@model Matissa.Models.Servicio

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="col-12 container detalle text-center">
    <link rel="stylesheet" href="~/css/servicios/servicios.css">
    <div class="col-12  container-fluid ">
        <div class="row titulo-detalle">
            <div class="col-12">
                <h1>Detalle de Servicios</h1>
            </div>
        </div>
    </div>
  
    <div class="row justify-content-center cuadro">
        <div class="col-md-6">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.NombreServicio)</th>
                        <td>@Html.DisplayFor(model => model.NombreServicio)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Descripción)</th>
                        <td>@Html.DisplayFor(model => model.Descripción)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Duración)</th>
                        <td>@Html.DisplayFor(model => model.Duración)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Precio)</th>
                        <td>@Html.DisplayFor(model => model.Precio)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Estado)</th>
                        <td>@Html.DisplayFor(model => model.Estado)</td>
                    </tr>


                </tbody>
            </table>
        </div>
    </div>
        
    <div class="row justify-content-center">
        <div class="col-md-6">
            <a asp-action="Edit" asp-route-id="@Model?.IdServicio" class="btn btn-warning">Editar</a> |
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </div>
</div>

Matissa/Views/Servicios/Edit.cshtml
@model Matissa.Models.Servicio

@{
    ViewData["Title"] = "editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/citas/create.css">
<div class="container-fluid titulo-citas">
    <div class="row">
        <div class="col-12">
            <h1>Editar Servicio</h1>
        </div>
    </div>
</div>
<div class="row">
    <form asp-action="Edit">
        <div class="col-md-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdServicio" class="control-label"></label>
                <input asp-for="IdServicio" class="form-control rounded-pill custom-input" />
                <span asp-validation-for="IdServicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreServicio" class="control-label"></label>
                <input asp-for="NombreServicio" class="form-control rounded-pill custom-input" />
                <span asp-validation-for="NombreServicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripción" class="control-label"></label>
                <input asp-for="Descripción" class="form-control rounded-pill custom-input" />
                <span asp-validation-for="Descripción" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duración" class="control-label"></label>
                <input asp-for="Duración" class="form-control rounded-pill custom-input" />
                <span asp-validation-for="Duración" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control rounded-pill custom-input" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control rounded-pill custom-input" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-warning" />
                <a class="btn btn-dark" asp-action="Index">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Matissa/Views/Servicios/Index.cshtml
@model IEnumerable<Matissa.Models.Servicio>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/servicios/Servicios.css">
<div class="container-fluid titulo-citas">
    <div class="row">
        <div class="col-12">
            <h1 class="pt-2">Listado de Servicios</h1>
        </div>
    </div>
</div>

<div class="container-fluid container">
    <div class="row d-flex">
        <div class="col-md-5 mb-3">
            <div class="form-floating">
                <input type="text" class="form-control rounded-pill" id="searchInput">
                <label for="inputBuscar" class="label-buscar"><i class="fa-solid fa-magnifying-glass"></i> Buscar por servicio...</label>
            </div>
        </div>
        <div class="col-md-3 mb-3 d-flex justify-content-end">
            <button onclick="window.location.href = '@Url.Action("Create", "Servicios")';" class="btn crear">
                <p class="rounded-pill">Crear Servicio <i class="fa-solid fa-circle-plus icon" style="font-size: 20px; margin-left:10px "></i></p>
            </button>
        </div>
    </div>
</div>
<br />
<br />
<table class="table" style="width: 90%;margin:auto" id="tablaServicios" table-striped table-bordered">
    <thead style="background-color: lightgray;">
        <tr>
            <th style="background-color: lightgray">
                @Html.DisplayNameFor(model => model.IdServicio)
            </th>
            <th style="background-color: lightgray">
                @Html.DisplayNameFor(model => model.NombreServicio)
            </th>
            <th style="background-color: lightgray ">
                @Html.DisplayNameFor(model => model.Descripción)
            </th>
            <th style="background-color: lightgray ">
                @Html.DisplayNameFor(model => model.Duración)
            </th>
            <th style="background-color: lightgray ">
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th style="background-color: lightgray ">
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th style="background-color: lightgray ">
                Operaciones
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                if (item != null)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdServicio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NombreServicio)
                        </td>
                        <td>
                            @(item.Descripción != null ? Html.DisplayFor(modelItem => item.Descripción) : Html.Raw("No hay descripción disponible"))
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Duración)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Precio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Estado)
                        </td>

                        <td>
                            <a asp-action="Edit" asp-route-id="@item.IdServicio"><i class="fa-solid fa-pencil" style="color:#3CC3BD;"></i></a> |
                            <a asp-action="Details" asp-route-id="@item.IdServicio"><i class="fa-sharp fa-solid fa-eye" style="color:#929292"></i></a> |
                            <a asp-action="Delete" asp-route-id="@item.IdServicio"><i class="fa-sharp fa-solid fa-circle-xmark" style="color:#929292"></i></a>
                        </td>
                    </tr>
                }
            }
        }

        <script>

            const searchInput = document.getElementById('searchInput');

            searchInput.addEventListener('input', function () {
                const searchTerm = searchInput.value.toLowerCase();


                const rows = document.querySelectorAll('#tablaServicios tbody tr');

                rows.forEach(function (row) {
                    const nombreServicio = row.querySelector('td:first-child').textContent.toLowerCase();

                    if (nombreServicio.includes(searchTerm)) {
                        row.style.display = '';
                    } else {
                        row.style.display = 'none';
                    }
                });
            });
        </script>
    </tbody>
</table>