Matissa/Controllers/VentaServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Matissa.Models;
using Microsoft.AspNetCore.Authorization;

namespace Matissa.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class VentaServiciosController : Controller
    {
        private readonly dbMatissaNETContext _context;

        public VentaServiciosController(dbMatissaNETContext context)
        {
            _context = context;
        }

        // GET: VentaServicios
        public async Task<IActionResult> Index(string searchString)
        {
            var ventas = from v in _context.VentaServicios select v;

            if (!String.IsNullOrEmpty(searchString))
            {
                ventas = ventas.Where(v =>
                    v.IdCita.ToString().Contains(searchString) ||
                    v.ValorVenta.ToString().Contains(searchString) ||
                    v.FechaVenta.ToString().Contains(searchString) ||
                    v.FormaPago.Contains(searchString) 
                );
            }

            return View(await ventas.ToListAsync());
        }




        // GET: VentaServicios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VentaServicios == null)
            {
                return NotFound();
            }

            var ventaServicio = await _context.VentaServicios
                .FirstOrDefaultAsync(m => m.IdVentaServicio == id);
            if (ventaServicio == null)
            {
                return NotFound();
            }

            return View(ventaServicio);
        }

        // GET: VentaServicios/Create
        public IActionResult Create()
        {
            var citas = _context.Cita.ToList();

            if (citas != null && citas.Any())
            {
                ViewBag.Citas = new SelectList(citas, "IdCita", "IdCita"); // Utiliza solo la propiedad IdCita para el SelectList
            }
            else
            {
                ViewBag.Citas = new SelectList(new List<Citum>(), "IdCita", "IdCita");
            }

            return View();
        }




        // POST: VentaServicios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVentaServicio,IdCita,ValorVenta,FechaVenta,FormaPago,Estado")] VentaServicio ventaServicio)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Agregar mensajes de registro para verificar los datos recibidos
                    Console.WriteLine($"IdCita: {ventaServicio.IdCita}");
                    Console.WriteLine($"ValorVenta: {ventaServicio.ValorVenta}");
                    Console.WriteLine($"FechaVenta: {ventaServicio.FechaVenta}");
                    Console.WriteLine($"FormaPago: {ventaServicio.FormaPago}");
                    Console.WriteLine($"Estado: {ventaServicio.Estado}");

                    _context.Add(ventaServicio);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Puedes agregar un registro de la excepción para depurar
                    Console.WriteLine(ex.Message);
                    return RedirectToAction(nameof(Create));
                }
            }
            // Si llegas aquí, significa que ModelState no es válido
            // Puedes añadir un mensaje de error o log para depuración
            return View(ventaServicio);
        }


        // GET: VentaServicios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VentaServicios == null)
            {
                return NotFound();
            }

            var ventaServicio = await _context.VentaServicios.FindAsync(id);
            if (ventaServicio == null)
            {
                return NotFound();
            }
            return View(ventaServicio);
        }

        // POST: VentaServicios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdVentaServicio,IdCita,ValorVenta,FechaVenta,FormaPago,Estado")] VentaServicio ventaServicio)
        {
            if (id != ventaServicio.IdVentaServicio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ventaServicio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VentaServicioExists(ventaServicio.IdVentaServicio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ventaServicio);
        }

        // GET: VentaServicios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VentaServicios == null)
            {
                return NotFound();
            }

            var ventaServicio = await _context.VentaServicios
                .FirstOrDefaultAsync(m => m.IdVentaServicio == id);
            if (ventaServicio == null)
            {
                return NotFound();
            }

            return View(ventaServicio);
        }

        // POST: VentaServicios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VentaServicios == null)
            {
                return Problem("Entity set 'dbMatissaNETContext.VentaServicios'  is null.");
            }
            var ventaServicio = await _context.VentaServicios.FindAsync(id);
            if (ventaServicio != null)
            {
                _context.VentaServicios.Remove(ventaServicio);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VentaServicioExists(int id)
        {
          return (_context.VentaServicios?.Any(e => e.IdVentaServicio == id)).GetValueOrDefault();
        }
    }
}

Matissa/Views/VentaServicios/Create.cshtml
@model Matissa.Models.VentaServicio

@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<div class="container">
    <h4>VentaServicio</h4>
    <hr />
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="IdCita" class="control-label"></label>
                    <select asp-for="IdCita" class="form-control" asp-items="@ViewBag.Citas"></select>
                    <span asp-validation-for="IdCita" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ValorVenta" class="control-label"></label>
                    <input asp-for="ValorVenta" class="form-control" />
                    <span asp-validation-for="ValorVenta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FechaVenta" class="control-label"></label>
                    <input asp-for="FechaVenta" class="form-control" />
                    <span asp-validation-for="FechaVenta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FormaPago" class="control-label"></label>
                    <input asp-for="FormaPago" class="form-control" />
                    <span asp-validation-for="FormaPago" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Estado" class="control-label"></label>
                    <input asp-for="Estado" class="form-control" />
                    <span asp-validation-for="Estado" class="text-danger"></span>
                </div>

                <div class="form-group text-center">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div class="text-center">
    <a asp-action="Index">Volver a la Lista</a>
</div>

Matissa/Views/VentaServicios/Delete.cshtml
@model Matissa.Models.VentaServicio

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<h3>¿Estás seguro de que deseas eliminar esto?</h3>
<div>
    <h4>VentaServicio</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCita)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCita)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValorVenta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorVenta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaVenta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaVenta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FormaPago)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FormaPago)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="IdVentaServicio" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Volver a la Lista</a>
    </form>
</div>

Matissa/Views/VentaServicios/Details.cshtml
@model Matissa.Models.VentaServicio

@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles</h1>

<div>
    <h4>VentaServicio</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCita)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCita)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValorVenta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorVenta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaVenta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaVenta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FormaPago)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FormaPago)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdVentaServicio" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver a la Lista</a>
</div>

Matissa/Views/VentaServicios/Edit.cshtml
@model Matissa.Models.VentaServicio

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<div class="container">
    <h4>VentaServicio</h4>
    <hr />
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdVentaServicio" />
                <div class="form-group">
                    <label asp-for="IdCita" class="control-label"></label>
                    <input asp-for="IdCita" class="form-control" />
                    <span asp-validation-for="IdCita" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ValorVenta" class="control-label"></label>
                    <input asp-for="ValorVenta" class="form-control" />
                    <span asp-validation-for="ValorVenta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FechaVenta" class="control-label"></label>
                    <input asp-for="FechaVenta" class="form-control" />
                    <span asp-validation-for="FechaVenta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FormaPago" class="control-label"></label>
                    <input asp-for="FormaPago" class="form-control" />
                    <span asp-validation-for="FormaPago" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Estado" class="control-label"></label>
                    <input asp-for="Estado" class="form-control" />
                    <span asp-validation-for="Estado" class="text-danger"></span>
                </div>
                <div class="form-group text-center">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div class="text-center">
    <a asp-action="Index" class="btn btn-secondary">Volver a la Lista</a>
</div>

Matissa/Views/VentaServicios/Index.cshtml
@model IEnumerable<Matissa.Models.VentaServicio>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/ventas/Ventas.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />

<div class="container-fluid titulo-ventas">
    <div class="row">
        <div class="col-12">
            <h1>Listado de ventas</h1>
        </div>
    </div>
</div>
<div class="container-fluid p-5 mb-5">
    <div class="row">
        <div class="label-buscar col-12">
            <form asp-action="Index" asp-controller="VentaServicios" method="get">
                <div class="form-floating">
                    <input type="text" class="form-control rounded-pill buscar-venta" id="searchString" name="searchString" placeholder="">
                    <label for="searchString" class="label-buscar"><i class="fa-solid fa-magnifying-glass"></i>Buscar venta</label>
                </div>
                <!-- Puedes dejar el botón oculto si no deseas mostrarlo -->
                <!--<input type="submit" value="Buscar" class="btn btn-primary" style="display: none;" />-->
            </form>
        </div>
        <div class="col-4">
            <a asp-action="Create" class="crear-venta">
                <p class="rounded-pill" style="padding-top: 8px;">Generar reporte de ventas<i class="fa-regular fa-square-plus" style="font-size: 30px; margin-left:10%; margin-top:5px; "></i></p>
            </a>
        </div>
        <div class="col-4">
            <a asp-action="Create" class="crear-venta">
                <p class="rounded-pill" style="padding-top: 8px;">Consultar venta de servicios<i class="fa-regular fa-square-plus" style="font-size: 30px; margin-left:10%; margin-top:5px; "></i></p>
            </a>
        </div>
        <div class="col-4">
            <a asp-action="Create" class="crear-venta">
                <p class="rounded-pill" style="padding-top: 8px;">Consultar venta de pedidos<i class="fa-regular fa-square-plus" style="font-size: 30px; margin-left:10%; margin-top:5px; "></i></p>
            </a>
        </div>
    </div>
</div>

<table class="table table-bordered p-3" style="width: 95%; margin-left: 25px;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCita)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorVenta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaVenta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FormaPago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCita)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorVenta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaVenta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FormaPago)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdVentaServicio"><i class="fas fa-edit"></i></a> |
                    <a asp-action="Details" asp-route-id="@item.IdVentaServicio"><i class="fas fa-info-circle"></i></a> |
                    <a asp-action="Delete" asp-route-id="@item.IdVentaServicio"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>