Matissa/Models/DetalleCompra.cs
using System;
using System.Collections.Generic;

namespace Matissa.Models
{
    public partial class Detallecompra
    {
        public int IdDetalleCompra { get; set; }
        public int IdCompra { get; set; }
        public int IdProducto { get; set; }
        public float PrecioUnitario { get; set; }
        public int Cantidad { get; set; }
        public float CostoTotalUnitario { get; set; }

        public virtual Compra IdCompraNavigation { get; set; } = null!;
        public virtual Producto IdProductoNavigation { get; set; } = null!;
    }
}

Matissa/Controllers/DetalleComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using Matissa.Models;
using matissa.Models;
using Microsoft.AspNetCore.Authorization;

namespace matissa.Controllers
{
    [Authorize(Roles = "Administrador,Clientes")]
    public class DetalleComprasController : Controller
    {
        private readonly dbMatissaNETContext _context;
        private static List<ServicioModel> servicioModels = new List<ServicioModel>();

        public DetalleComprasController(dbMatissaNETContext context)
        {
            _context = context;
        }

        // GET: DetalleCompras
        public async Task<IActionResult> Index(int id, int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10;

            var queryDetalleCompra = _context.DetalleCompras.Include(d => d.IdCompraNavigation).Include(d => d.IdProductoNavigation).Include(d => d.IdProveedorNavigation);

            var detalleCompra = await queryDetalleCompra
                .Where(c => c.IdCompra == id)
                .ToListAsync();

            return View(detalleCompra.ToPagedList(pageNumber, pageSize));
        }

        // GET: DetalleCompras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DetalleCompras == null)
            {
                return NotFound();
            }

            var detalleCompra = await _context.DetalleCompras
                .Include(d => d.IdCompraNavigation)
                .Include(d => d.IdProductoNavigation)
                .Include(d => d.IdProveedorNavigation)
                .FirstOrDefaultAsync(m => m.IdDetalleCompra == id);
            if (detalleCompra == null)
            {
                return NotFound();
            }

            return View(detalleCompra);
        }

        [HttpGet]
        public IActionResult AgregarProducto(ServicioModel model)
        {
            servicioModels.Add(model);

            // Puedes realizar otras operaciones con el detalle si es necesario
            Console.WriteLine($"Detalle recibido:{model.idProducto} {model.idProveedor} {model.nombreProducto} {model.nombreProveedor} {model.cantidad} {model.precio} {model.costoTotal}");
            foreach (var detall in servicioModels)
            {
                Console.WriteLine($"Detalle almacenado:{model.idProducto} {model.idProveedor} {model.nombreProducto} {model.nombreProveedor} {model.cantidad} {model.precio} {model.costoTotal}");
            }
            return Json(new { success = true, message = "Detalle guardado" });
        }

        [HttpGet]
        public IActionResult RemoveProducto(int idProducto)
        {
            ServicioModel productoRemove = servicioModels.FirstOrDefault(d => d.idProducto == idProducto);
            if (productoRemove != null)
            {
                servicioModels.Remove(productoRemove);
                Console.WriteLine($"Detalle con ID {productoRemove.idProducto} eliminado.");
            }
            else
            {
                Console.WriteLine($"Detalle no encontrado.");
            }
            Console.WriteLine("Lista después de la eliminación:");
            foreach (var detalle in servicioModels)
            {
                Console.WriteLine($"ID: {detalle.idProducto}");
            }
            return Json(new { success = true, message = "Detalle guardado" });
        }

        [HttpGet]
        public IActionResult DataProducto(int idProducto)
        {
            var producto = _context.Productos.Find(idProducto);
            if (producto == null)
            {
                return NotFound();
            }
            return Ok(producto);
        }

        [HttpGet]
        public IActionResult DataProveedor(int idProveedor)
        {
            var proveedor = _context.Proveedors.Find(idProveedor);
            if (proveedor == null)
            {
                return NotFound();
            }
            return Ok(proveedor);
        }

        // GET: DetalleCompras/Create
        public IActionResult Create()
        {
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra");
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto");
            ViewData["IdProveedor"] = new SelectList(_context.Proveedors, "IdProveedor", "IdProveedor");
            return View();
        }

        // POST: DetalleCompras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDetalleCompra,IdCompra,IdProducto,IdProveedor,PrecioUnitario,Cantidad,CostoTotalUnitario")] DetalleCompra detalleCompra)
        {
            if (detalleCompra != null)
            {
                var idCompra = ObtenerCompraID();
                double totalComprado = 0;

                foreach(var item in servicioModels)
                {
                    var producto = _context.Productos.Find(item.idProducto);
                    Console.WriteLine(producto.SaldoInventario);
                    Console.WriteLine("#####################################################################");

                    var idDetalleCompra = ObtenerDetalleCompraID();
                    detalleCompra.IdDetalleCompra = idDetalleCompra;
                    detalleCompra.IdCompra = idCompra;

                    detalleCompra.IdProducto = item.idProducto;
                    detalleCompra.IdProveedor = item.idProveedor;
                    detalleCompra.PrecioUnitario = item.precio;
                    detalleCompra.Cantidad = item.cantidad;
                    detalleCompra.CostoTotalUnitario = item.costoTotal;

                    _context.DetalleCompras.Add(detalleCompra);
                    await _context.SaveChangesAsync();

                    totalComprado += item.costoTotal;

                    producto.SaldoInventario += item.cantidad;
                    _context.Productos.Update(producto);
                }

                var compra = _context.Compras.Find(idCompra);

                if(compra != null)
                {
                    compra.CostoTotalCompra = totalComprado;
                    _context.Compras.Update(compra);
                    await _context.SaveChangesAsync();
                }

                servicioModels.Clear();
                return RedirectToAction("Index", "Compras");
            }
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra", detalleCompra.IdCompra);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detalleCompra.IdProducto);
            ViewData["IdProveedor"] = new SelectList(_context.Proveedors, "IdProveedor", "IdProveedor", detalleCompra.IdProveedor);
            return NotFound(detalleCompra);
        }

        public int ObtenerCompraID()
        {
            var idCompra = _context.Compras.Max(c => (int?)c.IdCompra) ?? 1;
            return idCompra;
        }

        public int ObtenerDetalleCompraID()
        {
            var idDetalleCompra = _context.DetalleCompras.Max(c => (int?)c.IdDetalleCompra) ?? 0;
            return idDetalleCompra + 1;
        }

        // GET: DetalleCompras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DetalleCompras == null)
            {
                return NotFound();
            }

            var detalleCompra = await _context.DetalleCompras.FindAsync(id);
            if (detalleCompra == null)
            {
                return NotFound();
            }
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra", detalleCompra.IdCompra);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detalleCompra.IdProducto);
            ViewData["IdProveedor"] = new SelectList(_context.Proveedors, "IdProveedor", "IdProveedor", detalleCompra.IdProveedor);
            return View(detalleCompra);
        }

        // POST: DetalleCompras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDetalleCompra,IdCompra,IdProducto,IdProveedor,PrecioUnitario,Cantidad,CostoTotalUnitario")] DetalleCompra detalleCompra)
        {
            if (id != detalleCompra.IdDetalleCompra)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detalleCompra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetalleCompraExists(detalleCompra.IdDetalleCompra))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra", detalleCompra.IdCompra);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detalleCompra.IdProducto);
            ViewData["IdProveedor"] = new SelectList(_context.Proveedors, "IdProveedor", "IdProveedor", detalleCompra.IdProveedor);

Matissa/Views/DetalleCompras/Create.cshtml
@model matissa.Models.DetalleCompra

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/producto.css" asp-append-version="true" />
<script src="~/js/producto.js" asp-append-version="true"></script>


<div class="container-fluid titulo-proveedor" id="ocultar">
    <div class="row">
        <div class="col">
            <h1>Detalles de la compra</h1>
        </div>
    </div>
</div>
<div class="container text-center">
        <form asp-action="Create" method="post" class="border-bottom border-1 border-dark">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="IdProducto" class="control-label">Producto</label>
                        <select asp-for="IdProducto" id="idProducto" class="rounded-pill text-center form-control border border-1 border-dark" asp-items="ViewBag.IdProducto" data-url="@Url.Action("DataProducto", "DetalleCompras")" onchange="dataProducto();">
                            <option disabled selected>-- Selecciones un producto --</option>
                        </select>
                    </div>
                    <div>
                    <input id="nombreProducto" class="rounded-pill form-control text-center border border-1 border-dark" readonly />
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="IdProveedor" class="control-label">Proveedor</label>
                        <select asp-for="IdProveedor" id="idProveedor" class="rounded-pill text-center form-control border border-1 border-dark" asp-items="ViewBag.IdProveedor" data-url="@Url.Action("DataProveedor", "DetalleCompras")" onchange="dataProveedor();">
                            <option disabled selected>-- Seleccione un proveedor --</option>
                        </select>
                    </div>
                    <div>
                        <input id="nombreProveedor" class="rounded-pill text-center form-control border border-1 border-dark" readonly />
                    </div>
                </div>
             </div>
            <div class="row mt-3">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="PrecioUnitario" class="control-label mt-3"></label>
                        <input asp-for="PrecioUnitario" id="precio" class="rounded-pill text-center form-control border border-1 border-dark" value="0" />
                        <span asp-validation-for="PrecioUnitario" class="text-danger" readonly></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Cantidad" class="control-label mt-3"></label>
                        <input asp-for="Cantidad" id="cantidad" onchange="costoTotalUnitario()" class="rounded-pill text-center form-control border border-1 border-dark" />
                        <span asp-validation-for="Cantidad" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="CostoTotalUnitario" class="control-label mt-3"></label>
                        <input asp-for="CostoTotalUnitario" id="costoTotal" class="rounded-pill form-control border text-center border-1 border-dark" readonly value="0" />
                        <span asp-validation-for="CostoTotalUnitario" class="text-danger"></span>
                    </div>
                </div>
            </div>
        <div class="row mt-3">
                <div class="col text-end">
                    <a asp-action="DeleteCompra" asp-controller="Compras">
                        <input type="button" class="boton-cancelar rounded-pill" value="Cancelar" />
                    </a>
                </div>
                <div class="col text-start">
                    <input type="button" value="Crear" data-bs-toggle="modal" data-bs-target="#exampleModal" class="boton-aceptar rounded-pill" />
                </div>
            </div>
            <div class="modal fade" id="exampleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="staticBackdropLabel">Aviso</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            ¿Estas seguro de que quieres crear la compra?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="boton-cancelar rounded-pill" data-bs-dismiss="modal">Cancelar</button>
                            <input type="submit" value="Crear" class="boton-aceptar rounded-pill" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-3 mb-3 agregarProducto">
                    <button type="button" class="mt-3 boton-agregar btn cancel-btn border border-1 border-dark rounded-pill" id="btnAgregarC" onclick="agregarCompra()" style="width: 100%">
                        Agregar detalle
                        <i class="fa-solid fa-plus"></i>
                    </button>
                </div>
            </div>
        </form>
    <div class="container mt-5 container-tabla">
            <table class="tabla text-center" id="tablaProductos">
                <thead>
                    <tr>
                        <th>#</th>
                        <th colspan="2">Producto</th>
                        <th colspan="2">Proveedor</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Costo Total</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>

        </div>
    <script>
        var listProducts = [];
        function agregarCompra() {
            let producto = document.getElementById("idProducto").value;
            let proveedor = document.getElementById("idProveedor").value;
            let nombreProducto = document.getElementById("nombreProducto").value;
            let nombreProveedor = document.getElementById("nombreProveedor").value;
            let cantidad = document.getElementById("cantidad").value;
            let precio = document.getElementById("precio").value;
            let costoTotal = document.getElementById("costoTotal").value;

            var subtotal = precio * cantidad;

            var obj = {
                idProducto: producto,
                idProveedor: proveedor,
                nombreProducto: nombreProducto,
                nombreProveedor: nombreProveedor,
                cantidad: cantidad,
                precio: precio,
                costoTotal: costoTotal
            }
            let indiceRegister = listProducts.findIndex(detalle => detalle.idProducto === producto);
            if (indiceRegister == -1) {
                listProducts.push(obj);

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("AgregarProducto","DetalleCompras")", // Reemplaza con la URL de tu controlador
                    contentType: "application/json; charset=utf-8",
                    data: obj,
                    success: function (response) {
                        // Manejar la respuesta del servidor si es necesario
                        console.log(response.message);

                    },
                    error: function (error) {
                        console.error("Error al guardar detalles", error);
                    }
                });

                mostrarDetalles();
            } else {
                alert("El producto ya existe en la lista");
            }
        }

        function mostrarDetalles() {
            // Limpiar el contenido actual del tbody
            var tbody = document.getElementById("tablaProductos").getElementsByTagName("tbody")[0];
            tbody.innerHTML = "";
            // Crear las filas con detalles y agregarlas al tbody
            for (var i = 0; i < listProducts.length; i++) {
                var detalle = listProducts[i];

                // Crear una nueva fila en el tbody
                var row = tbody.insertRow(i);

                // Insertar celdas con los datos del detalle en la fila
                var cellIndex = row.insertCell(0);
                cellIndex.innerHTML = i + 1;

                var cellProducto = row.insertCell(1);
                cellProducto.innerHTML = detalle.idProducto;

                var cellNombreProducto = row.insertCell(2);
                cellNombreProducto.innerHTML = detalle.nombreProducto;

                var cellProveedor = row.insertCell(3);
                cellProveedor.innerHTML = detalle.idProveedor;

                var cellNombreProveedor = row.insertCell(4);
                cellNombreProveedor.innerHTML = detalle.nombreProveedor;

                var cellCantidad = row.insertCell(5);
                cellCantidad.innerHTML = detalle.cantidad;

                var cellPrecio = row.insertCell(6);
                cellPrecio.innerHTML = detalle.precio;

                var cellCostoTotal = row.insertCell(7);
                cellCostoTotal.innerHTML = detalle.costoTotal;

                var cellDelete = row.insertCell(8);
                cellDelete.innerHTML = `
                    <button type="button" class="btn" onclick="removeProducto(${detalle.idProducto})">
                                <i class="fa-solid fa-trash" style="color: #3cc3bd;"></i>
                    </button>`
                // Puedes agregar más celdas según sea necesario
            }
        }

        function removeProducto(idProducto) {
            let indiceRemove = listProducts.findIndex(detalle => detalle.idProducto === idProducto);
            listProducts.splice(indiceRemove, 1);

            $.ajax({
                url: "@Url.Action("RemoveProducto","DetalleCompras")",
                type: "GET",
                data: { idProducto: idProducto },
                success: function (response) {
                    console.log(response.message);
                },
                error: function (error) {
                    console.error("Error al guardar detalles", error);
                }
            });

            mostrarDetalles();
        }

        function dataProducto() {
            $(document).ready(function () {
                var productId = $("#idProducto").val(); // Obtener el ID del producto desde algún lugar en tu página
                $.ajax({
                    url: $("#idProducto").data("url"), // Ruta al controlador y acción
                    type: "GET",
                    data: { idProducto: productId },
                    success: function (data) {
                        // Manejar los datos del producto devueltos por el servidor
                        let precio = document.getElementById("precio").value = data.precioVenta;
                        let nombre = document.getElementById("nombreProducto").value = data.nombreProducto;
                        console.log(data);
                        // Aquí puedes actualizar tu interfaz de usuario con los datos del producto
                    },
                    error: function () {
                        alert("Error al obtener los datos del producto");
                    }
                });
            });
        }

        function dataProveedor() {
            $(document).ready(function () {
                var proveedorId = $("#idProveedor").val(); // Obtener el ID del producto desde algún lugar en tu página
                $.ajax({
                    url: $("#idProveedor").data("url"), // Ruta al controlador y acción
                    type: "GET",
                    data: { idProveedor: proveedorId },
                    success: function (data) {
                        // Verifica si los datos están definidos antes de asignarlos
                        if (data && data.nombreProveedor) {
                            let nombre = document.getElementById("nombreProveedor").value = data.nombreProveedor;
                            console.log(data);
                        } else {
                            console.error("Error: Los datos del proveedor no son válidos");
                        }
                    },
                    error: function () {
                        alert("Error al obtener los datos del producto");
                    }
                });
            });
        }
        function costoTotalUnitario() {
            let cantidad = document.getElementById("cantidad").value;
            let precio = document.getElementById("precio").value;

            let costoTotal = cantidad * precio;

            console.log(costoTotal);

            document.getElementById("costoTotal").value = costoTotal;
        }
    </script>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Matissa/Views/DetalleCompras/Delete.cshtml
@model matissa.Models.DetalleCompra

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetalleCompra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostoTotalUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostoTotalUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCompraNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCompraNavigation.IdCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProductoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoNavigation.IdProducto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProveedorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProveedorNavigation.IdProveedor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdDetalleCompra" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Matissa/Views/DetalleCompras/Details.cshtml
@model matissa.Models.DetalleCompra

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>DetalleCompra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostoTotalUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostoTotalUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCompraNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCompraNavigation.IdCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProductoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoNavigation.IdProducto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProveedorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProveedorNavigation.IdProveedor)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdDetalleCompra">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Matissa/Views/DetalleCompras/Edit.cshtml
@model matissa.Models.DetalleCompra

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>DetalleCompra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdDetalleCompra" />
            <div class="form-group">
                <label asp-for="IdCompra" class="control-label"></label>
                <select asp-for="IdCompra" class="form-control" asp-items="ViewBag.IdCompra"></select>
                <span asp-validation-for="IdCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProducto" class="control-label"></label>
                <select asp-for="IdProducto" class="form-control" asp-items="ViewBag.IdProducto"></select>
                <span asp-validation-for="IdProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProveedor" class="control-label"></label>
                <select asp-for="IdProveedor" class="form-control" asp-items="ViewBag.IdProveedor"></select>
                <span asp-validation-for="IdProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioUnitario" class="control-label"></label>
                <input asp-for="PrecioUnitario" class="form-control" />
                <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CostoTotalUnitario" class="control-label"></label>
                <input asp-for="CostoTotalUnitario" class="form-control" />
                <span asp-validation-for="CostoTotalUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}